name: shutla_v2
description: Implementation of a simple Mobile Demand Responsive Transport System
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.1
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  flutter_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3
  image_picker: ^0.8.6+2
  event_bus: ^2.0.0
  my_widgets:
    git:
      url: https://github.com/cs-onah/my_widgets.git
  package_info_plus: ^4.0.1
  device_info_plus: ^9.0.1
  firebase_messaging: ^14.6.1
  firebase_core: ^2.11.0
  hooks_riverpod:
  google_maps_flutter: ^2.2.7
  collection:
  intl: ^0.18.1
  date_format: ^2.0.7
  permission_handler: ^10.2.0
  url_launcher:
  share_plus:
  geolocator: ^9.0.2
  local_auth: ^2.1.6
  geocoding: ^2.1.0
  equatable:
  flutter_local_notifications: ^15.1.0+1
  timezone: ^0.9.2
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"
  hive_generator: # flutter packages pub run build_runner build
  build_runner:
  freezed: ^2.3.2
  change_app_package_name: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/launcher_icon.png"
    background_color: "#ffffffff"
    theme_color: "#DA251C"
  windows:
    generate: true
    image_path: "assets/images/launcher_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/launcher_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/json/
    - assets/fonts/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400